name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  python-formatting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Black
        run: pip install black

      - name: Run Black
        run: black --check app.py

  unit_tests:
    needs: python-formatting
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Unit Tests
        env: 
          FLASK_SECRET_KEY: ${{ secrets.FLASK_SECRET_KEY }}
        run: |
          python -m unittest app_test.py


  javascript-build:
    runs-on: ubuntu-latest
    needs: python-formatting

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Node.js Dependencies
        run: |
          cd client
          npm install

      - name: Build React Project
        run: |
          cd client
          npm run build

  build_to_ghcr:
    needs: [unit_tests, javascript-build]  # build only runs if test is successful
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.USER_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/alvasi/central-api:latest
          platforms: linux/amd64

  # deploy_to_aci:
  #   # if: github.event_name == 'workflow_dispatch'
  #   runs-on: ubuntu-latest
  #   needs: build_to_ghcr
  #   steps:
  #     - name: 'Login via Azure CLI'
  #       uses: azure/login@v1
  #       with:
  #         creds: ${{ secrets.AZURE_CREDENTIALS }}

  #     - name: 'Deploy to Azure Container Instances'
  #       uses: 'azure/aci-deploy@v1'
  #       with:
  #         resource-group: sse_group
  #         dns-name-label: central-api
  #         image: ghcr.io/alvasi/central-api:latest
  #         registry-login-server: ghcr.io
  #         registry-username: alvasi
  #         registry-password: ${{ secrets.USER_TOKEN }}
  #         secure-environment-variables: FLASK_SECRET_KEY=${{ secrets.FLASK_SECRET_KEY }}
  #         name: central-api
  #         location: 'UK South'
